name: Sync to Target Git Repository

on:
  push:
    branches:
      - main  # 触发同步的分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取完整的提交历史

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add target repository
        run: |
          git remote add target http://${{ secrets.TARGET_GIT_USERNAME }}:${{ secrets.TARGET_GIT_PASSWORD }}@icloud630.myqnapcloud.com:3000/ethan021/Deep-Live-Cam.git

      - name: Push to target repository
        env:
          TARGET_GIT_USERNAME: ${{ secrets.TARGET_GIT_USERNAME }}
          TARGET_GIT_PASSWORD: ${{ secrets.TARGET_GIT_PASSWORD }}
        run: |
          git push target main --force
